services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.network=traefik-net"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--accesslog=true"
      - "--log.level=DEBUG"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./traefik.prod.yml:/etc/traefik/traefik.prod.yml:ro
#      - ./dynamic.prod.yml:/etc/traefik/dynamic.prod.yml:ro
#      - ./certs:/certs #
    networks:
      - traefik-net

networks:
  traefik-net:
    name: traefik-net
    external: true
