http:
  routers:
    dashboard:
      rule: "Host(`traefik.172.17.0.1`)"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

tls:
  certificatesResolvers:
    myresolver:
      acme:
        email: admin@172.17.0.1
        storage: /certs/acme.json
        httpChallenge:
          entryPoint: web
