FROM python:3.12-slim

WORKDIR /app
ENV PYTHONPATH="/app"
ENV ENV=dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7001", "--reload", "--log-level", "debug"]
