FROM python:3.11-slim

WORKDIR /app
ENV ENV=dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY run_migrations.sh .
RUN chmod +x run_migrations.sh

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD ["./run_migrations.sh"]