services:
  s3:
    image: minio/minio:latest
    container_name: minio
    restart: always
    env_file:
      - ../../../.env.prod
    expose:
      - "9000"
      - "9001"
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-internal

volumes:
  s3_data:

networks:
  app-internal:
    name: app-internal
    external: true
